version: "3"
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/srv/help
      - ./data:/srv/data
      - ./data/.parisneo:/root/.parisneo/
      - ./configs:/srv/configs
      - ./web:/srv/web
    ports: 
      - "9600:9600"
    logging:
      driver:  json-file
      options:
        max-file: "3"   # number of files or file count
        max-size: '10m'
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]